### PR TITLE
popdown notification and style

### PR DESCRIPTION
**Pull request by jpknoll**

### CODE REVIEW

**Comment by jpknoll** [comment]
screen shot 2016-10-22 at 11 04 59 pm

**Comment by jpknoll** [comment]
screen shot 2016-10-22 at 11 07 16 pm

**Comment by jpknoll** [comment]
popdown is on the actual page, so it should scroll away as you scroll down.

**Review by srkirkland — APPROVED** [review]

**Comment by deemanator** [comment]
Cool!! Thank you,  John!

**Pull request merged**
